PACKAGE_NAME=tuxedo-drivers
PACKAGE_VERSION=4.22.3

DEST_MODULE_LOCATION[0]="/kernel/lib/"
BUILT_MODULE_NAME[0]="clevo_acpi"
BUILT_MODULE_LOCATION[0]="src/"

DEST_MODULE_LOCATION[1]="/kernel/lib/"
BUILT_MODULE_NAME[1]="clevo_wmi"
BUILT_MODULE_LOCATION[1]="src/"

DEST_MODULE_LOCATION[2]="/kernel/lib/"
BUILT_MODULE_NAME[2]="tuxedo_keyboard"
BUILT_MODULE_LOCATION[2]="src/"

DEST_MODULE_LOCATION[3]="/kernel/lib/"
BUILT_MODULE_NAME[3]="uniwill_wmi"
BUILT_MODULE_LOCATION[3]="src/"

DEST_MODULE_LOCATION[4]="/kernel/lib/"
BUILT_MODULE_NAME[4]="gxtp7380"
BUILT_MODULE_LOCATION[4]="src/gxtp7380/"

DEST_MODULE_LOCATION[5]="/kernel/lib/"
BUILT_MODULE_NAME[5]="ite_8291"
BUILT_MODULE_LOCATION[5]="src/ite_8291/"

DEST_MODULE_LOCATION[6]="/kernel/lib/"
BUILT_MODULE_NAME[6]="ite_8291_lb"
BUILT_MODULE_LOCATION[6]="src/ite_8291_lb/"

DEST_MODULE_LOCATION[7]="/kernel/lib/"
BUILT_MODULE_NAME[7]="ite_8297"
BUILT_MODULE_LOCATION[7]="src/ite_8297/"

DEST_MODULE_LOCATION[8]="/kernel/lib/"
BUILT_MODULE_NAME[8]="ite_829x"
BUILT_MODULE_LOCATION[8]="src/ite_829x/"

DEST_MODULE_LOCATION[9]="/kernel/lib/"
BUILT_MODULE_NAME[9]="stk8321"
BUILT_MODULE_LOCATION[9]="src/stk8321/"

DEST_MODULE_LOCATION[10]="/kernel/lib/"
BUILT_MODULE_NAME[10]="tuxedo_compatibility_check"
BUILT_MODULE_LOCATION[10]="src/tuxedo_compatibility_check/"

DEST_MODULE_LOCATION[11]="/kernel/lib/"
BUILT_MODULE_NAME[11]="tuxedo_io"
BUILT_MODULE_LOCATION[11]="src/tuxedo_io/"

DEST_MODULE_LOCATION[12]="/kernel/lib/"
BUILT_MODULE_NAME[12]="tuxedo_nb02_nvidia_power_ctrl"
BUILT_MODULE_LOCATION[12]="src/tuxedo_nb02_nvidia_power_ctrl/"

DEST_MODULE_LOCATION[13]="/kernel/lib/"
BUILT_MODULE_NAME[13]="tuxedo_nb04_keyboard"
BUILT_MODULE_LOCATION[13]="src/tuxedo_nb04/"

DEST_MODULE_LOCATION[14]="/kernel/lib/"
BUILT_MODULE_NAME[14]="tuxedo_nb04_wmi_ab"
BUILT_MODULE_LOCATION[14]="src/tuxedo_nb04/"

DEST_MODULE_LOCATION[15]="/kernel/lib/"
BUILT_MODULE_NAME[15]="tuxedo_nb04_wmi_bs"
BUILT_MODULE_LOCATION[15]="src/tuxedo_nb04/"

DEST_MODULE_LOCATION[16]="/kernel/lib/"
BUILT_MODULE_NAME[16]="tuxedo_nb05_keyboard"
BUILT_MODULE_LOCATION[16]="src/tuxedo_nb05/"

DEST_MODULE_LOCATION[17]="/kernel/lib/"
BUILT_MODULE_NAME[17]="tuxedo_nb05_kbd_backlight"
BUILT_MODULE_LOCATION[17]="src/tuxedo_nb05/"

DEST_MODULE_LOCATION[18]="/kernel/lib/"
BUILT_MODULE_NAME[18]="tuxedo_nb05_power_profiles"
BUILT_MODULE_LOCATION[18]="src/tuxedo_nb05/"

DEST_MODULE_LOCATION[19]="/kernel/lib/"
BUILT_MODULE_NAME[19]="tuxi_acpi"
BUILT_MODULE_LOCATION[19]="src/tuxedo_tuxi/"

DEST_MODULE_LOCATION[20]="/kernel/lib/"
BUILT_MODULE_NAME[20]="tuxedo_tuxi_fan_control"
BUILT_MODULE_LOCATION[20]="src/tuxedo_tuxi/"

DEST_MODULE_LOCATION[21]="/updates/dkms"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
AUTOINSTALL="yes"
